app/loginMenus/__init__.py
from flask import Blueprint


login=Blueprint('loginMenus',__name__,url_prefix='/login',template_folder='templates')


#vincular archivo de rutras
from . import routes

app/loginMenus/routes.py
from app import *
from flask import session
from flask import Flask
from flask import render_template, request, redirect,session
from . import login



#Funcion que cierra la session 
@login.route('/logout')
def logout():
    session.clear()
    return redirect('acceso-login')


#LOGIN  CON LOS ROLES DE USUARIO


@login.route('/acceso-login')
def home():
    return render_template('login.html')   

@login.route('/admin')
def admin():
    return render_template('admin.html')   


 

@login.route('/acceso-login', methods= ["GET", "POST"])
def login():
   
    if request.method == 'POST' and 'username' in request.form and 'password' in request.form:
       
        _username = request.form['username']
        _password = request.form['password']

        cur = mysql.connection.cursor()
        cur.execute('SELECT * FROM usuarios WHERE username = %s AND password = %s', (_username, _password,))
        account = cur.fetchone()
      
        if account:
            session['logueado'] = True
            session['Id_user'] = account['Id_user']
            session['id_rol'] = account['id_rol']
            
            if session['id_rol']==1:
                return render_template("admin.html")
            elif session['id_rol']==2:
                return render_template("user.html")
        else:
            return render_template('login.html',mensaje="Hola su usuario o contraseña son incorrectas ")
  
  
  
  
  

app/loginMenus/templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Administrador</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/ADMIN.css')}}">
</head>
<body>
    <header>
        <h1>Menu Administrador</h1>
        <a href="{{ url_for('loginMenus.logout') }}"><button class="cerrar" >Cerrar Session</button></a>
    </header>


   


<div class="menu">

   <div class="btn-group" role="group" aria-label="Basic outlined example">
   <a href="{{ url_for('registroValoracion.registroval') }}"> <button  type="button" class="btn btn-outline-primary">Registrar valoracion</button>    </a>
   <a href="{{ url_for('registroValoracion.listarvaloracion') }}"> <button  type="button" class="btn btn-outline-primary">Listado valoracion</button></a>
    <button type="button" class="btn btn-outline-primary">Garantias</button>
  </div>
</div>
<footer>
    <h1>Mecanica-Master </h1>
</footer>


</body>
</html>

app/loginMenus/templates/login.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Login Usuarios</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/LOGIN.css') }}">


</head>


<header>

<H1 class="h1"> Login </H1>

</header>

<body>

<form action="acceso-login" method="POST" enctype="multipart/form-data">

<label class="label1" for="">Usuario:</label>
<input type="text"placeholder="Usuario" name="username"  required="true">

<label class="label2" for="">Contraseña:</label>
<input type="text"placeholder="Contraseña" name="password"  required="true">
    
<button class="button">INGRESAR</button>

</form>
</body>

</html>

app/loginMenus/templates/registro_valoracion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro de la valoracion de un vehiculo</title>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/REGISTRO_VALORACION.css') }}">

</head>
<body>
    <header>
        <a href="{{ url_for('logout') }}"><button class="cerrar" >Cerrar Session</button></a>


<h1>Registro de Valoracion</h1>

    </header>

<form action="">


    <input type="text"placeholder="Diagnostico del Vehiculo" name="" id="">


    <button href="">Registrar</button>
</form>

<footer>
    <h1>Mechanical Tecnology</h1>
</footer>

</body>
</html>

app/loginMenus/templates/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menu  Usuario</title>

    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/USER.css')}}">
</head>
<body>
    <header>
        <h1>Menu Usuario</h1>
        <a href="{{ url_for('loginMenus.logout') }}"><button class="cerrar" >Cerrar Session</button></a>
    </header>
<H1 style="background-color: BLACK;COLOR:azure;"></H1>
    

<footer>
    <h1>Mecanica-Master</h1>
</footer>
</body>
</html>